# Site
repository: sproogen/resume-theme
favicon: images/favicon.png

# Content configuration version
version: 2

# Personal info
name: Furfaro Fabien
title: Data & Computer Vision Scientist - Independent Researcher
email: fabien.furfaro@gmail.com
website: fabienfrfr.herokuapp.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  fabienfrfr
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: fabienfrfr
linkedin_username: fabien-furfaro
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Website link
  icon: fas fa-globe
  url: https://fabienfrfr.herokuapp.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Fabien and I'm a complex systems physicist with a particular interest in interdisciplinary projects. I am interested in machine learning, data innovation and skills sharing. Today, I apply my skills in data analysis and machine learning.
  
  I am most skilled in: <mark>Python</mark> and <mark>Modelization</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: An Artificial Neural Network Functionalized by Evolution
        link: github.com/fabienfrfr/AFF
        # link_text: Project Website
        additional_links:
          - title:  fabienfrfr/AFF
            icon: fab fa-sistrix
            url: https://arxiv.org/abs/2205.10118
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is some of the most interesting research I have been able to conduct. (with my thesis, of course)
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>PyTorch</mark> and applied mathematics in neural network. I have learned many skills through this and been I'm very proud of having this in my portfolio.
          
      - layout: top-middle
        title: How to illustrate the beauty of mathematics?
        link: github.com/fabienfrfr/INSTA
        # link_text: Project Website
        additional_links:
          - title:  fabienfrfr/INSTA
            icon: fab fa-instagram
            url: www.instagram.com/fabienfrfr
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Finding a way to mix animation art and math and can be a good way to put yourself in a mathematician's shoes when looking at shapes.
        description: | # this will include new lines to allow paragraphs
          This project was carried out during the covid period after my thesis. It was a good way to get back to an old passion, drawing. Each of the animations illustrates fundamental <mark>Physics</mark> problems of complex systems.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Matière et Systèmes Complexes Lab
        link: www.msc.univ-paris-diderot.fr
        # link_text: boringcompany.com
        sub_title: PhD in Biophysics
        caption: September 2015 - September 2019
        additional_links:
          - title:  HAL/Thesis
            icon: fab fa-sistrix
            url: hal.archives-ouvertes.fr/tel-03405136/
        quote: >
          Characterization of the NODAL signaling pathway during embryonic stem cell differentiation. It's a way to control cell differentiation trajectory. Management : <mark>Benoit Sorre</mark> and <mark>Pascal Hersen</mark>.
        description: | # this will include new lines to allow paragraphs
            The aim of this work was to study the influence of the temporal stimulation of different morphogens on the expression of the "Nodal" locus and on the differentiation of stem cells. To control the temporal profile of the morphogen concentration sent to cells, we use an automated microfluidic cell culture chip that allows us to observe individual cell responses in real time with the fluorescence microscope. For this work, you need to have great skills in engineering, adaptability and image analysis.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Académie Créteil-Paris-Versailles
        link: agreg.org
        caption: 2020 - 2021
        sub_title: Mathematics Agrégation
        quote: >
          Established in 1808, the agrégation is a competitive examination for civil service in the French public education system.
        description: | # this will include new lines to allow paragraphs
          During my learning of neural networks and machine learning, I took advantage of my year for a complete refresher in mathematics. I didn't validate the competition, but this learning allowed me to be completely up to date on the theory of neural networks and machine learning.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EPJE Article
        caption: 2015
        sub_title: Vincent Fleury
        additional_links:
          - title:  EPJE/Article
            icon: fab fa-sistrix
            url: link.springer.com/article/10.1140/epje/i2015-15006-7
        quote: >
          Buckling along boundaries of elastic contrast as a mechanism for early vertebrate morphogenesis.
        description: | # this will include new lines to allow paragraphs
          We have investigated the mechanism of formation of the body of a typical vertebrate, the chicken. We find that the body forms initially by folding at boundaries of stiffness contrast. These boundaries are dynamic lines, separating domains of different cell sizes, that are advected in a deterministic thin-film visco-elastic flow.



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks, research and engineering, some of my other interests and hobbies are:
      - Creative Coding
      - Build <mark>Educational Game</mark> [See Here](https://fabienfrfr.itch.io/break-the-brain)
      - Hiking
      - Cycling
      - CrossFit
      - Volunteering

      Also, an overview when we mix code, art and mathematics
      
      ![Instagram](/images/Sprite_landscape.jpg "arcimboldo&fourier")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
